services:
  magma:
    container_name: magma
    image: help14/magma
    restart: unless-stopped
    volumes:
      - ./data/:/app/data
    ports:
      - '7001:7001'
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    command: --interval 30
